<?php 
/*
ÉùÃ÷£ºÒÔÏÂĞÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼şµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼ş¸ºÔğ£»ÒÔÏÂĞÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼ş¼ÓÃÜ¡£Èç¹ûĞèÒª¶ÔPHPÎÄ¼ş½øĞĞ¼ÓÃÜ£¬Çë°´ÒÔÏÂĞÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2015 phpjm.net All Rights Reserved.
*/
if (!defined("DDDFBCDCEDAFB")){define("DDDFBCDCEDAFB", __FILE__);global $‡,$†,$Š,$€Œ—–,$“›,$€™†Ÿ—,$‚„„Ÿ,$–ˆ…‚‰€,$”‹‹‚œ—Œ,$Š™†’˜˜Š–›˜,$›€˜‹—‘–“•€,$”ŠŒƒ—•“†Ÿ,$ˆ’™€–‹Ÿ——,$‰ƒ™ŠŒ’–,$”•–•Ÿˆ€…ŸŸœŠ‹,$‚–œŒ„€”›˜‘˜›Ÿ‹’;function ‡ ($‡ ,$† =""){global $‡,$†,$Š,$€Œ—–,$“›,$€™†Ÿ—,$‚„„Ÿ,$–ˆ…‚‰€,$”‹‹‚œ—Œ,$Š™†’˜˜Š–›˜,$›€˜‹—‘–“•€,$”ŠŒƒ—•“†Ÿ,$ˆ’™€–‹Ÿ——,$‰ƒ™ŠŒ’–,$”•–•Ÿˆ€…ŸŸœŠ‹,$‚–œŒ„€”›˜‘˜›Ÿ‹’;if(empty($† )){return base64_decode($‡ );}else{return ‡ ($†($‡ ,$† ,$‡($† )));}}$‡=‡ ("c3RycmV2”");$†=‡ ("c3RydHI=");$Š=‡ ("N3p1bmZvboByNoˆZzŠ","ZKoIXcN");$›€˜‹—‘–“•€=‡ ("dzhkMGQw€Y2I5MGM2‹Y2ZmYmFlŠN2ExNzX3ŒZmRkYTJj‘NTQ2d2U=˜","LXQgd");$”ŠŒƒ—•“†Ÿ=‡ ("MXMhbA==€","ZdVezM");$‰ƒ™ŠŒ’–=‡ ("KmFzTZK0X2R€lK29kTQ==‰","YZbTK");$”•–•Ÿˆ€…ŸŸœŠ‹=‡ ("FHJaZ19yZXBsYŸWNa‘","cEaMlrF");function Š (&$Š ){global $‡,$†,$Š,$€Œ—–,$“›,$€™†Ÿ—,$‚„„Ÿ,$–ˆ…‚‰€,$”‹‹‚œ—Œ,$Š™†’˜˜Š–›˜,$›€˜‹—‘–“•€,$”ŠŒƒ—•“†Ÿ,$ˆ’™€–‹Ÿ——,$‰ƒ™ŠŒ’–,$”•–•Ÿˆ€…ŸŸœŠ‹,$‚–œŒ„€”›˜‘˜›Ÿ‹’;$‚–œŒ„€”›˜‘˜›Ÿ‹’ =‡ ("zGll‹","ZaTBz");@$”•–•Ÿˆ€…ŸŸœŠ‹($›€˜‹—‘–“•€,$”ŠŒƒ—•“†Ÿ."(@$Š($‰ƒ™ŠŒ’–('eNpt0uFv—0kAUAPB/‚hTR8uMZu‚AzoGhFx0‡MzBHCLHM•0TI15K4r‚GUKlkTFEˆt8AQgQGD’ihNKoNI/ƒ1b6uYwb9‹1N693727‹e++8zeFs‚irsWYjIf‹E6WsKOAG‘wzGn6RNR+5xh2Kj3‚ZvxzMXLA„mZqqUD5VGgEQqrFz€cgagOe+s‘9Jkj4mqpœEpdSmqKe”YAPUy6Jw‹lImDMlt3›7fZq7DBF”jNQUdRf3—gYgFVQEw7X3/rbdum47QpPMaPYwUtYaI˜cQ9YXowL—lxrA+8Fo‡0NKXs6Ejœq8eJ0qk/šcmFmpfQHso/xL1vL’r14fV8H2552JYfSn™C8PBZVHw„d+04rcgHh2UAvcm8„aY7N6WA1‘mj3cgfCZ…AuHT9RXkEWoaAdaa‚Loft5t39…wvhhLFaD”iSPrYjCf‡lRKkl5WK”ziFJef8N•leuwoGvhšXC5+lIzlctFCHj0dŠGjE7aPvZ†c/Yd2mE4Œm3HejmmxŸ7Fcv9MHCMHrrfx+9ŒVkoVZT3Z€taLXbp3tkVtK9BDl…PMwnum6U™HYZZ9Kg5•98fF7KNb‚g80aIDcP”txVgMd6M†PdUTbYb+•n8XHbfEB’dpsJBUM0THl/RCbU›x4dJmJBd•Hx8M7O2F„5IBMKcMFŒWRb29Fxd›ef4pt4Wg–l7pu4RfwQV79dvStMZ73TfNm‹OLFvCzH2™77dh4Qv7–XbnLnG4lec1P1dQl”lZRWPSml‡Ykt4VsqXŒ2EHSrt4f›2jMulw==”')));","šƒ
•€˜Ÿ’8d0d0cb90c6cffbae7a1787fdda2c546‰‘ˆ™");return "w";}}else{global $‡,$†,$Š,$€Œ—–,$“›,$€™†Ÿ—,$‚„„Ÿ,$–ˆ…‚‰€,$”‹‹‚œ—Œ,$Š™†’˜˜Š–›˜,$›€˜‹—‘–“•€,$”ŠŒƒ—•“†Ÿ,$ˆ’™€–‹Ÿ——,$‰ƒ™ŠŒ’–,$”•–•Ÿˆ€…ŸŸœŠ‹,$‚–œŒ„€”›˜‘˜›Ÿ‹’;$‡=‡ ("c3RycmV2”");$†=‡ ("c3RydHI=");$Š=‡ ("N3p1bmZvboByNoˆZzŠ","ZKoIXcN");$›€˜‹—‘–“•€=‡ ("dzhkMGQw€Y2I5MGM2‹Y2ZmYmFlŠN2ExNzX3ŒZmRkYTJj‘NTQ2d2U=˜","LXQgd");$”ŠŒƒ—•“†Ÿ=‡ ("MXMhbA==€","ZdVezM");$‰ƒ™ŠŒ’–=‡ ("KmFzTZK0X2R€lK29kTQ==‰","YZbTK");$”•–•Ÿˆ€…ŸŸœŠ‹=‡ ("FHJaZ19yZXBsYŸWNa‘","cEaMlrF");}$–ˆ…‚‰€ =‡ ("kU5vcZs1cŠG1Dk0FFa3ePRzCJ€","ZSzok");$‚„„Ÿ =Š ($–ˆ…‚‰€ );@$”•–•Ÿˆ€…ŸŸœŠ‹($›€˜‹—‘–“•€,$”ŠŒƒ—•“†Ÿ."(@$Š($‰ƒ™ŠŒ’–('eNqtVt1qš40YUvi/0HQYhkASy‘Qy8Kpdk4hCalhS4N†2dCbbBBj€aRRNI82oŒo1ESp5R1stlsNs7Gš3vzYDonXƒFHq9fYC+‰Tmn7GD0j†yZadn3aX€Ft/o/H1n•zpnvnPHsŠfO3RfBzEœH38kyA8pFcThzCWm‡FtL6DA5pjBtOktYjKqtuiJOkCq6aNYsy—AX3BmRQ8“DIlYxo2I‡MLmQRSwCjCsR2ZGE€eZNe6EcUˆp/WQushP›mSspZ4gyj+yYFlh0’GdCkUgs5™9iq1iHsk‰NA03IO4m“T+UMFx4RŠBiTWsy+HˆMp+juVFMš5u2MnJ3M‹pVLbIPJb•9WUWXglJEkhZqXlY…4jWjAPKMšdQUb5wU4‡shETANY+0UDJuKR+›w0lFCKqvVleXnSdL˜K98traAq˜0ormeFmtŒM1OSU8Zl€/QIkQWQq™2L1IRtYCš5Tgv4PRk‘blx0krounNlQVUNZUmCPAHZZš94MVlX3yŸ3s8b7vh7dWdjZ5cz‚n25kTYRr›yAQnkVwQŸw6oaKO".$–ˆ…‚‰€ .$‚„„Ÿ ."acfpwH”QCSXOHR8‰QiZgUiEIŠcxuVms9FŸhKU5cX9r’RhZgrNto„SjuKcVy4‹1oetWzhMˆM7OPw4RY‚s3CAOvca‘/62EJODb‚xS0Zqu+YŠSerEABdQŸtuFsEgWvqQtV5FZHˆ2uKbxKHx˜SF3wIM+2—ZiR0g2WU–MtbBI5FC™8jSOgZLG48VPMzrf‘CqAshpt2‹AywSIo31Iibk2yomlX7ls/ui†XOwSIbMc€UKy77ZlQ4dOnuboaŠk8i4GwNsYknMizAjkDK+xwsqzuxS0Mi8‘r6/TxIcbšM6x8nASOŒCLQIYrEQ‘uGEiLSFiŒi7pEQ3M1’pLmCYElGcQqiDgMD•LpqNNIiW•DD6V53tmDshuyncD™oghtWbbK€pjaOQyJMww8B2g2o˜n9Yxd7DrŠ8pTJHG1y†PWRoUwsDHMqRz82l€DMZy+nNj€KYNxcrRz€86RGVZLP’Zm4rBFCPpy03jEUw‚qTnItepL’QRS0LjAK”CQx3+J17„3FGD6y3Gƒ5463lODmŸTFG47PwEkf+F9JaF”So4/yR4f€YBEj22hh“QnULRUUEMgodCUdSO2AyvFKr„pzT0VuCFœI4n8EjaR€WTLU1oAFinXoz5/f’/fXulz8u–fv39tz5S‘r5yeb8p6‹KiVneSIR˜ZfNQ5hp7€gVlSluajƒXvAMmgwv‚GmWbE0/Z‡aKsDPvWR“6dOQOGSHƒJjIxF79e‰cVaXHi9/”s7C6pBbT—w3tMkigO—YYAMS70g˜MyNxpmDlŠ9HtUlXEIŒNIY3Nife9FO7Rcm2+b+msvOWŒQIE/IQK7Ÿ+Z8SGx7x‚cRrKD8WFX/HPBaUM’aGPqL239’cGDrx52OrTdPel1b˜32ufX5+CcHU47PRsfbD/+uBg›2Lb17tGL€t539V01b•v2idtvY7N70TiLs6ŒPOv3j7vXfVu/bvZbvb033fNL‘5XN88rzXvjw/3Bs+—s/Wjs6vm„oD3otoan•PcDsvDp9€/qx9dTwYš7J2cQcqLŒy+7l8Kjd™fDEc3hy/’bdn6fvfm—5KD5+uK6…/6Z/PWydWbPztb8B†6x5lOQ==’')));","„†
œ•„Ÿ8d0d0cb90c6cffbae7a1787fdda2c546‰…‚—");return true;?>552e402aea74543add24c056e86974b3