<?php exit; ?> 



2016-01-12 10:36:20------>array (
  0 => 'UPDATE `go_admin` SET `logintime`=\'1452566180\' WHERE (`uid`=\'1\')',
  1 => 'UPDATE `go_admin` SET `loginip`=\'60.168.45.44\' WHERE (`uid`=\'1\')',
) 



2016-01-12 10:57:28------>array (
  0 => 'UPDATE `go_admin` SET `logintime`=\'1452567448\' WHERE (`uid`=\'1\')',
  1 => 'UPDATE `go_admin` SET `loginip`=\'60.168.45.44\' WHERE (`uid`=\'1\')',
) 



2016-01-12 10:57:36------>array (
  0 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 790',
  1 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 786',
  2 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 784',
  3 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 791',
  4 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 780',
  5 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 789',
  6 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 785',
  7 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 787',
  8 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 783',
  9 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 903',
  10 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 792',
  11 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 793',
  12 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 794',
  13 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 795',
  14 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 796',
  15 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 797',
  16 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 798',
  17 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 799',
  18 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 800',
  19 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 801',
  20 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 802',
  21 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 803',
  22 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 804',
  23 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 805',
  24 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 806',
  25 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 807',
  26 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 808',
  27 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 809',
  28 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 810',
  29 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 811',
  30 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 812',
  31 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 813',
  32 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 814',
  33 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 815',
  34 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 816',
  35 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 817',
  36 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 818',
  37 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 819',
  38 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 820',
  39 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 821',
  40 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 822',
  41 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 823',
  42 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 824',
  43 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 825',
  44 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 826',
  45 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 827',
  46 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 828',
  47 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 829',
  48 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 830',
  49 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 831',
  50 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 832',
  51 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 964',
  52 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 833',
  53 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 834',
  54 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 835',
  55 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 836',
  56 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 899',
  57 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 837',
  58 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 838',
  59 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 839',
  60 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 840',
  61 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 841',
  62 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 842',
  63 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 843',
  64 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 844',
  65 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 845',
  66 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 846',
  67 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 847',
  68 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 848',
  69 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 849',
  70 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 850',
  71 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 851',
  72 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 852',
  73 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 853',
  74 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 854',
  75 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 855',
  76 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 856',
  77 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 857',
  78 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 858',
  79 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 859',
  80 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 860',
  81 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 861',
  82 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 862',
  83 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 900',
  84 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 863',
  85 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 864',
  86 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 865',
  87 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 866',
  88 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 867',
  89 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 868',
  90 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 869',
  91 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 870',
  92 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 871',
  93 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 872',
  94 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 873',
  95 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 874',
  96 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 875',
  97 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 876',
  98 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 877',
  99 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 878',
  100 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 879',
  101 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 880',
  102 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 881',
  103 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 882',
  104 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 883',
  105 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 884',
  106 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 885',
  107 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 886',
  108 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 887',
  109 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 888',
  110 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 889',
  111 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 890',
  112 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 891',
  113 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 892',
  114 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 893',
  115 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 894',
  116 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 895',
  117 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 896',
  118 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 897',
  119 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 898',
  120 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 902',
  121 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 904',
  122 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 905',
  123 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 906',
  124 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 907',
  125 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 908',
  126 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 909',
  127 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 910',
  128 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 911',
  129 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 912',
  130 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 913',
  131 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 914',
  132 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 915',
  133 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 916',
  134 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 917',
  135 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 918',
  136 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 919',
  137 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 920',
  138 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 921',
  139 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 922',
  140 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 923',
  141 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 924',
  142 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 925',
  143 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 926',
  144 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 927',
  145 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 928',
  146 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 929',
  147 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 930',
  148 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 931',
  149 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 932',
  150 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 933',
  151 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 934',
  152 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 935',
  153 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 936',
  154 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 937',
  155 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 938',
  156 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 939',
  157 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 940',
  158 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 941',
  159 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 942',
  160 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 943',
  161 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 944',
  162 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 945',
  163 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 946',
  164 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 947',
  165 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 948',
  166 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 949',
  167 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 950',
  168 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 951',
  169 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 952',
  170 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 953',
  171 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 954',
  172 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 955',
  173 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 956',
  174 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 957',
  175 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 958',
  176 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 959',
  177 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 960',
  178 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 961',
  179 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 962',
  180 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 963',
  181 => 'UPDATE `go_member` SET money = money + 1, jingyan = jingyan + 0, score = score + 0 WHERE uid = 965',
) 



